---
- name: Initialize Debian-family Development Environment
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    java_version: "21.0.8-sem"
    nvm_version: "v0.40.3"
    node_version: "22"

  roles:
    - { role: basic_tools,      tags: [basic_tools] }
    - { role: github_ssh,       tags: [github] }
    - { role: workspace,        tags: [workspace] }
    - { role: shell_setup,      tags: [shell] }
    - { role: chrome,           tags: [chrome] }
    - role: gnome_extensions
      tags: [gnome]
      when: "'GNOME' in (ansible_facts['env']['XDG_CURRENT_DESKTOP'] | default(''))"
    - { role: docker,           tags: [docker] }
    - { role: sdkman,           tags: [sdkman] }
    - { role: nodejs,           tags: [nodejs] }
    - { role: ides,             tags: [ides] }
