---
- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: yes

- name: Update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u
  become: yes
  changed_when: true

- name: Reload udev rules
  ansible.builtin.command:
    cmd: udevadm control --reload-rules
  become: yes
  changed_when: true
